Numpy

In [1]:
!pip install numpy

In [4]:
import numpy as np

##create arrays using nump

arr = np.array([1,2,3,4,5,6,7])

print(arr)
print(type(arr))
print(arr.shape)


[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
(7,)


In [ ]:
arr2 = np.array([1,2,3,4,5,6,7])
arr2.reshape(1,7) #1 row and 7 columns
#print(a)

array([[1, 2, 3, 4, 5, 6, 7]])

In [17]:
arr3 = np.array([[1,2,3,4,5,6,7],[2,3,4,5,6,7,8]])
arr3.shape
print(arr3)

[[1 2 3 4 5 6 7]
 [2 3 4 5 6 7 8]]


In [25]:
np.arange(0,12,2).reshape(6,1)  #start , end , step size

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [26]:
np.ones((3,4))  #3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
arr4 = np.array([[1,2,3,4,5,6,7],[2,3,4,5,6,7,8]])

print(arr4.ndim)
print(arr4.size)
print(arr4.dtype)
print(arr4.itemsize)
print(arr4.nbytes)

2
14
int64
8
112


In [ ]:
#numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

#element wise addition
arr3 = arr1 + arr2
print(arr3)


#element wise subtraction
arr4 = arr2 - arr1  
print(arr4)

#element wise multiplication
arr5 = arr1 * arr2
print(arr5)


#square root
arr6 = np.sqrt(arr1)    
print(arr6)



[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [35]:
#array slicing and indexing
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr[2:7])  #slicing from index 2 to 6
print(arr[:5])    #slicing from start to index 4
print(arr[5:])    #slicing from index 5 to end
print(arr[-5:])   #slicing last 5 elements
print(arr[::2])   #slicing with step size 2

[30 40 50 60 70]
[10 20 30 40 50]
[ 60  70  80  90 100]
[ 60  70  80  90 100]
[10 30 50 70 90]
